### PR TITLE
<Feature> - Enable tsconfig paths (config only)

### PR DESCRIPTION
**Pull request by mchl18**
- Sets deps and configs for ts-config-paths. 
- Depends on Mocha upgrade.
- enables to import via `@dilecy` as alias for `src/renderer`.
- Going forward, anything which is imported from another module* should be imported by using the alias.
- Going forward, we should have one barrel file in `src/renderer` and one barrel inside each bottom-level folder. The barrel in `src/renderer` should point to the bottom level barrels. This way we can achieve import structure like 
`import { action, RootState } from '@dilecy/core'. ` or `import { StyledButton, StyledButtonOutlined } from '@dilecy/shared'.
- Going forward, we should consider avoiding `default export`'s within a module or generally. They have no benefit for us while they can obfuscate the name of the exported class.

\*module => represented by any folder directly below `src/renderer`

I can later merge the actually updated imports from the other branch.

### CODE REVIEW

**Comment by gabber7** [comment]
Thanks for the PR. 

The changes will create a conflict with #3. If possible I propose to change the base branch and resolve the conflicts.

**Comment by mchl18** [comment]
I cannot change my base to a branch within my own repo, from here, only to dilecy branches.
I would then just wait with this for the time being.

**Comment by mchl18** [comment]
Actually I will close this and reopen it whenever the mocha upgrade goes through.
Should not have created this in the first place.

**Comment by mchl18** [comment]
now everything seems to check out, also for test and webdev

**Comment by mchl18** [comment]
Yes, that was for testing purposes, sorry!

My rule for imports: if it is further up that two directories, use the '@dilecy' import.
That way, I also try to not stack anything deeper than four folders. The top level folders (core, feature, ....) should be the entry points. This way we do not need to create more path aliases, just index.ts files for each top-level folder.

**Pull request merged**
